---
- name: Debug variables
  ansible.builtin.import_tasks: 00_debug.yml

- name: Validate inputs
  ansible.builtin.import_tasks: 05_validate.yml

- name: Prepare controller staging area
  ansible.builtin.import_tasks: 10_prep_controller.yml

- name: Export scheduled tasks on source
  ansible.builtin.import_tasks: 20_export_on_source.yml

- name: Fetch exported tasks to controller
  ansible.builtin.import_tasks: 30_fetch_to_controller.yml

- name: Push tasks to destination hosts
  ansible.builtin.import_tasks: 40_push_to_destination.yml

- name: Import tasks on destination hosts
  ansible.builtin.import_tasks: 50_import_on_destination.yml

- name: Clean up controller files
  ansible.builtin.import_tasks: 60_clean_up_controller.yml

- name: Clean up source host files
  ansible.builtin.import_tasks: 70_clean_up_source.yml

- name: Clean up destination host files
  ansible.builtin.import_tasks: 80_clean_up_destinations.yml
